"""Candidate frames: what the fly sees at a junction.

Each option is its own 320x180 frame on a light background (Stonkfly's chart
aesthetic: light background was required for meaningful KC activation, see
docs/model.md "dark chart barely activated KCs"). One candidate per consult,
round-robin, exactly like Stonkfly presents assets.
"""

import os

FRAME_W, FRAME_H = 320, 180
LIGHT_BG = (235, 240, 249)
INK = (19, 36, 71)


def thumbs_dir(run_dir):
    return os.path.join(run_dir, "thumbs")


def thumb_path(run_dir, image_id):
    return os.path.join(thumbs_dir(run_dir), f"{image_id}.jpg")


def ensure_thumb(run_dir, node, session=None):
    """Fetch (or reuse) a node's thumbnail. Mock corridors pre-generate files."""
    import requests

    path = thumb_path(run_dir, node["id"])
    if os.path.exists(path):
        return path
    os.makedirs(thumbs_dir(run_dir), exist_ok=True)
    if node["thumb"].startswith("mock://"):
        raise RuntimeError("mock thumbs must be generated by mockcorridor, not fetched")
    resp = (session or requests).get(node["thumb"], timeout=30)
    resp.raise_for_status()
    tmp = path + ".partial"
    with open(tmp, "wb") as f:
        f.write(resp.content)
    os.replace(tmp, path)
    return path


def option_frame(run_dir, node, option_letter):
    """Render one candidate as an RGB uint8 PNG frame; returns PNG bytes."""
    import io

    from PIL import Image, ImageDraw

    thumb = Image.open(thumb_path(run_dir, node["id"])).convert("RGB")
    # cover-resize into a 320x150 viewport
    target_w, target_h = FRAME_W, FRAME_H - 30
    scale = max(target_w / thumb.width, target_h / thumb.height)
    resized = thumb.resize(
        (int(thumb.width * scale) + 1, int(thumb.height * scale) + 1), Image.BILINEAR
    )
    x0 = (resized.width - target_w) // 2
    y0 = (resized.height - target_h) // 2
    viewport = resized.crop((x0, y0, x0 + target_w, y0 + target_h))

    im = Image.new("RGB", (FRAME_W, FRAME_H), LIGHT_BG)
    im.paste(viewport, (0, 0))
    d = ImageDraw.Draw(im)
    d.rectangle((0, FRAME_H - 30, FRAME_W, FRAME_H), fill=INK)
    d.text((8, FRAME_H - 22), f"FLY EYE  OPT {option_letter}", fill=(219, 229, 249))
    # small chevron pointing "ahead" - part of the display adapter, not game logic
    cx = FRAME_W - 28
    cy = FRAME_H - 15
    d.line((cx - 6, cy + 3, cx, cy - 4), fill=(219, 229, 249), width=2)
    d.line((cx, cy - 4, cx + 6, cy + 3), fill=(219, 229, 249), width=2)

    buf = io.BytesIO()
    im.save(buf, format="PNG")
    return buf.getvalue()
