"""Candidate frames: what the fly sees at a junction.

Each option is its own 320x180 frame on a light background (Stonkfly's chart
aesthetic: light background was required for meaningful KC activation, see
docs/model.md "dark chart barely activated KCs"). One candidate per consult,
round-robin, exactly like Stonkfly presents assets.

Goal-bias veil (v2): the thumbnail's brightness encodes how much the
candidate reduces straight-line distance to the goal compared to the fly's
current node. Brighter = closer to the nata. This is an engineered input, not
retinal physiology - the connectome still makes the decisions, but the visual
salience it reads is goal-directed. Strength is tunable via GOAL_SALIENCE_K
(per-junction delta gain), GOAL_SALIENCE_L (delta length scale, metres) and
GOAL_SALIENCE_ABS (absolute proximity gain for the "brighter near the goal"
ramp seen in the flycam).

v2 follow-up (2026-09-16): the brightness veil was measured neutral-to-
inverted against the real brain (per-junction corr ~+0.01, hz drift -1.8 Hz
across the full boost range) and is now OFF by default (GOAL_SALIENCE_K=0).
The goal channel is the chart-native goal meter: a dark column rendered like
Stonkfly's own chart ink whose height encodes how much closer the candidate
gets the fly to the nata. GOAL_METER_W / GOAL_METER_H size it; GOAL_SALIENCE_L
normalizes the delta.
"""

import os

FRAME_W, FRAME_H = 320, 180
LIGHT_BG = (235, 240, 249)
INK = (19, 36, 71)

GOAL_SALIENCE_K = 0.0
GOAL_SALIENCE_L = 3.0
GOAL_SALIENCE_ABS = 0.0

GOAL_METER_W = 26.0
GOAL_METER_H = 80.0


def meter_size(current, candidate, goal):
    """(width, height) of the chart-native goal meter.

    The column renders like chart ink on the light background - the visual
    domain Stonkfly's connectome was validated on. Height is linear in how
    much closer the candidate sits than the current node (saturated at
    +/-GOAL_SALIENCE_L metres). Deterministic and resume-safe.
    """
    from corridor import haversine_m

    cur = haversine_m(current["lat"], current["lng"], goal["lat"], goal["lng"])
    cand = haversine_m(candidate["lat"], candidate["lng"], goal["lat"], goal["lng"])
    length_m = float(os.environ.get("GOAL_SALIENCE_L", GOAL_SALIENCE_L))
    d = max(-1.0, min(1.0, (cur - cand) / max(1.0, length_m)))
    return (
        float(os.environ.get("GOAL_METER_W", GOAL_METER_W)),
        max(0.0, float(os.environ.get("GOAL_METER_H", GOAL_METER_H)) * (1.0 + d) / 2.0),
    )


def salience_params():
    """(k, length_m, abs_gain) from env, falling back to the defaults above."""

    def f(name, default):
        return float(os.environ.get(name, default))

    return (
        f("GOAL_SALIENCE_K", GOAL_SALIENCE_K),
        f("GOAL_SALIENCE_L", GOAL_SALIENCE_L),
        f("GOAL_SALIENCE_ABS", GOAL_SALIENCE_ABS),
    )


def goal_boost(current, candidate, goal):
    """Multiplicative brightness factor that encodes goal direction.

    delta > 0 means the candidate sits closer to the goal than the current
    node; those candidates come out brighter. The absolute proximity term adds
    a mild overall ramp so frames brighten as the fly approaches the nata.
    Deterministic: same inputs, same boost (resume-safe).
    """
    from corridor import haversine_m

    cur = haversine_m(current["lat"], current["lng"], goal["lat"], goal["lng"])
    cand = haversine_m(candidate["lat"], candidate["lng"], goal["lat"], goal["lng"])
    k, length_m, abs_gain = salience_params()
    delta = max(-1.0, min(1.0, (cur - cand) / max(1.0, length_m)))
    proximity = max(0.0, min(1.0, 1.0 - cand / max(1.0, cur)))
    boost = (1.0 + abs_gain * proximity) * (1.0 + k * delta)
    # clamp: keep the brightest candidate from clipping to uniform white (the
    # real brain needs image contrast for KC activation, not flat brightness)
    return max(0.4, min(1.5, boost))


def thumbs_dir(run_dir):
    return os.path.join(run_dir, "thumbs")


def thumb_path(run_dir, image_id):
    return os.path.join(thumbs_dir(run_dir), f"{image_id}.jpg")


def ensure_thumb(run_dir, node, session=None):
    """Fetch (or reuse) a node's thumbnail. Mock corridors pre-generate files."""
    import requests

    path = thumb_path(run_dir, node["id"])
    if os.path.exists(path):
        return path
    os.makedirs(thumbs_dir(run_dir), exist_ok=True)
    if node["thumb"].startswith("mock://"):
        raise RuntimeError("mock thumbs must be generated by mockcorridor, not fetched")
    resp = (session or requests).get(node["thumb"], timeout=30)
    resp.raise_for_status()
    tmp = path + ".partial"
    with open(tmp, "wb") as f:
        f.write(resp.content)
    os.replace(tmp, path)
    return path


def option_frame(run_dir, current, candidate, option_letter, goal):
    """Render one candidate as an RGB uint8 PNG frame; returns PNG bytes.

    current/candidate/goal are coordinate records ({lat, lng}) - the boost
    passed to the thumbnail is a pure function of them, so consulting and
    re-rendering (flycam) always produce identical bytes.
    """
    import io

    from PIL import Image, ImageDraw, ImageEnhance

    ensure_thumb(run_dir, candidate)
    thumb = Image.open(thumb_path(run_dir, candidate["id"])).convert("RGB")
    boost = goal_boost(current, candidate, goal)
    if abs(boost - 1.0) > 1e-6:
        thumb = ImageEnhance.Brightness(thumb).enhance(boost)
    # cover-resize into a 320x150 viewport
    target_w, target_h = FRAME_W, FRAME_H - 30
    scale = max(target_w / thumb.width, target_h / thumb.height)
    resized = thumb.resize(
        (int(thumb.width * scale) + 1, int(thumb.height * scale) + 1), Image.BILINEAR
    )
    x0 = (resized.width - target_w) // 2
    y0 = (resized.height - target_h) // 2
    viewport = resized.crop((x0, y0, x0 + target_w, y0 + target_h))

    im = Image.new("RGB", (FRAME_W, FRAME_H), LIGHT_BG)
    im.paste(viewport, (0, 0))
    d = ImageDraw.Draw(im)
    mw, mh = meter_size(current, candidate, goal)
    if mh > 1.0:
        mw = int(mw)
        d.rectangle(
            ((FRAME_W - mw) // 2, FRAME_H - 30 - int(mh), (FRAME_W + mw) // 2, FRAME_H - 32),
            fill=INK,
        )
    d.rectangle((0, FRAME_H - 30, FRAME_W, FRAME_H), fill=INK)
    d.text((8, FRAME_H - 22), f"FLY EYE  OPT {option_letter}", fill=(219, 229, 249))
    # small chevron pointing "ahead" - part of the display adapter, not game logic
    cx = FRAME_W - 28
    cy = FRAME_H - 15
    d.line((cx - 6, cy + 3, cx, cy - 4), fill=(219, 229, 249), width=2)
    d.line((cx, cy - 4, cx + 6, cy + 3), fill=(219, 229, 249), width=2)

    buf = io.BytesIO()
    im.save(buf, format="PNG")
    return buf.getvalue()
